server:
  port: 8880

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wiki?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 1Mysql@23
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml